spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/resellers?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update
    properties:
      hibernate:
        show_sql : true
        format_sql: true
        use_sql_comments: true

cloud:
  aws:
    credentials:
      access-key: test-key
      secret-key: test-key
    s3:
      bucket: test-bucket
      region: ap-northeast-2

